import React from 'react';
import { ShieldAlert, ArrowRight, Play, FileSearch, CheckCircle2, ShieldCheck } from 'lucide-react';

function App() {
  return <div className="min-h-screen bg-[#07090E] text-[#F3F4F6] font-sans">
    <nav className="border-b border-white/5 bg-black/20 backdrop-blur-md sticky top-0 z-50"><div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between"><div className="flex items-center gap-2"><ShieldAlert className="w-5 h-5 text-[#0066CC]"/><span className="font-semibold tracking-wide">PRIMHORA</span></div><a href="https://firsthour-ui-n4cc.onrender.com/" target="_blank" rel="noreferrer" className="bg-white/10 px-4 py-2 rounded-full font-medium">Explore product</a></div></nav>
    <main className="relative overflow-hidden"><div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[400px] bg-[#0066CC]/20 rounded-full blur-[120px] -z-10 pointer-events-none"/>
      <section className="max-w-7xl mx-auto px-6 pt-32 pb-24 text-center"><div className="inline-flex px-3 py-1.5 rounded-full border border-[#0066CC]/30 bg-[#0066CC]/10 text-[#0066CC] text-xs font-semibold uppercase tracking-widest mb-8">Financial Incident Investigation</div><h1 className="text-5xl sm:text-7xl font-bold tracking-tight mb-8 leading-[1.1]">When money moves wrong,<br/><span className="text-transparent bg-clip-text bg-gradient-to-r from-white to-white/40">know what you can prove.</span></h1><p className="text-lg text-white/50 max-w-2xl mx-auto mb-12 leading-relaxed">PRIMHORA reconstructs financial incidents from source records and fragmented evidence, verifies claims deterministically, and prepares an auditable evidence packet for human resolution.</p><div className="flex justify-center gap-4"><a href="https://firsthour-ui-n4cc.onrender.com/" target="_blank" rel="noreferrer" className="bg-white text-black px-8 py-4 rounded-full font-medium flex items-center gap-2">Explore the product <ArrowRight className="w-4 h-4"/></a><a href="#architecture" className="bg-white/5 border border-white/10 px-8 py-4 rounded-full font-medium flex items-center gap-2"><Play className="w-4 h-4"/> See how it works</a></div><p className="text-xs text-white/35 mt-8">Read-only by design. Demo data is synthetic. No money is moved by PRIMHORA.</p></section>
      <section id="architecture" className="max-w-7xl mx-auto px-6 py-24 border-t border-white/5"><div className="text-center mb-16"><h2 className="text-3xl font-bold mb-4">Three layers of authority</h2><p className="text-white/50 max-w-xl mx-auto">AI interprets. Deterministic systems establish financial truth. Humans resolve what the data cannot know.</p></div><div className="grid md:grid-cols-3 gap-8"><div className="bg-white/[0.02] border border-white/5 rounded-3xl p-8"><FileSearch className="w-10 h-10 text-[#0066CC] mb-6"/><h3 className="text-xl font-semibold mb-3">AI interprets</h3><p className="text-white/50 text-sm leading-relaxed">Unstructured evidence becomes candidate claims with source references. Candidate claims remain untrusted until verified.</p></div><div className="bg-white/[0.02] border border-white/5 rounded-3xl p-8"><CheckCircle2 className="w-10 h-10 text-emerald-500 mb-6"/><h3 className="text-xl font-semibold mb-3">Code establishes truth</h3><p className="text-white/50 text-sm leading-relaxed">Reconciliation, timestamps, amounts, identifiers and exposure come from deterministic source records and calculations.</p></div><div className="bg-white/[0.02] border border-white/5 rounded-3xl p-8"><ShieldCheck className="w-10 h-10 text-amber-500 mb-6"/><h3 className="text-xl font-semibold mb-3">Humans resolve uncertainty</h3><p className="text-white/50 text-sm leading-relaxed">Authorization and intent remain human responsibilities. PRIMHORA prepares evidence; it does not execute recovery.</p></div></div></section>
    </main></div>;
}

export default App;
