"""baseline_and_financial_types

Revision ID: c3e2717fbf5f
Revises: 
Create Date: 2026-09-15 23:44:40.583168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.entities
import app.models.risk


# revision identifiers, used by Alembic.
revision: str = 'c3e2717fbf5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



from sqlalchemy.engine.reflection import Inspector

def upgrade() -> None:
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    tables = inspector.get_table_names()
    
    if 'merchants' not in tables:
    
        """Upgrade schema."""
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('account_trust_states',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('tenant_id', sa.String(), nullable=False),
        sa.Column('entity_id', sa.String(), nullable=False),
        sa.Column('known_devices', app.models.risk.JSONVariant(), nullable=False),
        sa.Column('known_ips', app.models.risk.JSONVariant(), nullable=False),
        sa.Column('known_beneficiaries', app.models.risk.JSONVariant(), nullable=False),
        sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
        sa.Column('median_amount', sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column('mad_amount', sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column('total_transactions', sa.Integer(), nullable=False),
        sa.Column('active_incident_id', sa.String(), nullable=True),
        sa.Column('current_risk_score', sa.Float(), nullable=False),
        sa.Column('first_divergence_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_event_hash', sa.String(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'entity_id', name='uq_trust_state_tenant_entity')
        )
        op.create_table('graph_relationships',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('tenant_id', sa.String(), nullable=False),
        sa.Column('source_type', sa.String(), nullable=False),
        sa.Column('source_id', sa.String(), nullable=False),
        sa.Column('target_type', sa.String(), nullable=False),
        sa.Column('target_id', sa.String(), nullable=False),
        sa.Column('relation_type', sa.String(), nullable=False),
        sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
        sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
        sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_graph_relationships_tenant_id'), 'graph_relationships', ['tenant_id'], unique=False)
        op.create_index('ix_graph_source', 'graph_relationships', ['tenant_id', 'source_type', 'source_id'], unique=False)
        op.create_index('ix_graph_target', 'graph_relationships', ['tenant_id', 'target_type', 'target_id'], unique=False)
        op.create_table('risk_decisions',
        sa.Column('decision_id', sa.String(), nullable=False),
        sa.Column('tenant_id', sa.String(), nullable=False),
        sa.Column('entity_id', sa.String(), nullable=False),
        sa.Column('event_id', sa.String(), nullable=False),
        sa.Column('risk_probability', sa.Float(), nullable=False),
        sa.Column('risk_band', sa.String(), nullable=False),
        sa.Column('recommended_action', sa.String(), nullable=False),
        sa.Column('reason_codes', app.models.risk.JSONVariant(), nullable=False),
        sa.Column('supporting_events', app.models.risk.JSONVariant(), nullable=False),
        sa.Column('competing_hypotheses', app.models.risk.JSONVariant(), nullable=False),
        sa.Column('model_version', sa.String(), nullable=False),
        sa.Column('policy_version', sa.String(), nullable=False),
        sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('actual_outcome', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('decision_id')
        )
        op.create_index(op.f('ix_risk_decisions_entity_id'), 'risk_decisions', ['entity_id'], unique=False)
        op.create_index(op.f('ix_risk_decisions_tenant_id'), 'risk_decisions', ['tenant_id'], unique=False)
        op.create_table('risk_events',
        sa.Column('event_id', sa.String(), nullable=False),
        sa.Column('tenant_id', sa.String(), nullable=False),
        sa.Column('entity_id', sa.String(), nullable=False),
        sa.Column('event_type', sa.String(), nullable=False),
        sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('source_event_id', sa.String(), nullable=False),
        sa.Column('schema_version', sa.String(), nullable=False),
        sa.Column('payload', app.models.risk.JSONVariant(), nullable=False),
        sa.Column('payload_hash', sa.String(), nullable=False),
        sa.Column('previous_event_hash', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('event_id'),
        sa.UniqueConstraint('tenant_id', 'source', 'source_event_id', name='uq_risk_event_source')
        )
        op.create_index(op.f('ix_risk_events_entity_id'), 'risk_events', ['entity_id'], unique=False)
        op.create_index(op.f('ix_risk_events_event_time'), 'risk_events', ['event_time'], unique=False)
        op.create_index(op.f('ix_risk_events_event_type'), 'risk_events', ['event_type'], unique=False)
        op.create_index(op.f('ix_risk_events_tenant_id'), 'risk_events', ['tenant_id'], unique=False)
        op.create_table('tenants',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('audit_events',
        sa.Column('id', sa.String(length=40), nullable=False),
        sa.Column('incident_id', sa.String(length=32), nullable=False),
        sa.Column('actor', sa.String(length=16), nullable=False),
        sa.Column('actor_user_id', sa.String(length=32), nullable=False),
        sa.Column('event_type', sa.String(length=48), nullable=False),
        sa.Column('summary', sa.String(length=300), nullable=False),
        sa.Column('sources', app.models.entities.SafeJSON(), nullable=False),
        sa.Column('detail', app.models.entities.SafeJSON(), nullable=False),
        sa.Column('before_state', app.models.entities.SafeJSON(), nullable=False),
        sa.Column('after_state', app.models.entities.SafeJSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
        op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
        op.create_index(op.f('ix_audit_events_incident_id'), 'audit_events', ['incident_id'], unique=False)
        op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
        op.create_table('entity_links',
        sa.Column('id', sa.String(length=40), nullable=False),
        sa.Column('left_type', sa.String(length=32), nullable=False),
        sa.Column('left_id', sa.String(length=64), nullable=False),
        sa.Column('right_type', sa.String(length=32), nullable=False),
        sa.Column('right_id', sa.String(length=64), nullable=False),
        sa.Column('signal', sa.String(length=40), nullable=False),
        sa.Column('weight', sa.Float(), nullable=False),
        sa.Column('decision', sa.String(length=16), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_entity_links_left_id'), 'entity_links', ['left_id'], unique=False)
        op.create_index(op.f('ix_entity_links_right_id'), 'entity_links', ['right_id'], unique=False)
        op.create_index(op.f('ix_entity_links_tenant_id'), 'entity_links', ['tenant_id'], unique=False)
        op.create_table('merchants',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('category', sa.String(length=80), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('is_flagship', sa.Boolean(), nullable=False),
        sa.Column('tenant_id', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_merchants_tenant_id'), 'merchants', ['tenant_id'], unique=False)
        op.create_table('users',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('email', sa.String(length=160), nullable=False),
        sa.Column('display_name', sa.String(length=120), nullable=False),
        sa.Column('role', sa.String(length=24), nullable=False),
        sa.Column('api_token', sa.String(length=64), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_users_api_token'), 'users', ['api_token'], unique=True)
        op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
        op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
        op.create_table('contacts',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('merchant_id', sa.String(length=32), nullable=False),
        sa.Column('name', sa.String(length=160), nullable=False),
        sa.Column('type', sa.String(length=24), nullable=False),
        sa.Column('phone', sa.String(length=24), nullable=False),
        sa.Column('email', sa.String(length=160), nullable=False),
        sa.Column('upi_id', sa.String(length=80), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_contacts_created_at'), 'contacts', ['created_at'], unique=False)
        op.create_index(op.f('ix_contacts_merchant_id'), 'contacts', ['merchant_id'], unique=False)
        op.create_index(op.f('ix_contacts_tenant_id'), 'contacts', ['tenant_id'], unique=False)
        op.create_table('employees',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('merchant_id', sa.String(length=32), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('role', sa.String(length=80), nullable=False),
        sa.Column('comm_handle', sa.String(length=120), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_employees_merchant_id'), 'employees', ['merchant_id'], unique=False)
        op.create_index(op.f('ix_employees_tenant_id'), 'employees', ['tenant_id'], unique=False)
        op.create_table('evidence_artifacts',
        sa.Column('id', sa.String(length=40), nullable=False),
        sa.Column('incident_id', sa.String(length=32), nullable=False),
        sa.Column('merchant_id', sa.String(length=32), nullable=False),
        sa.Column('filename', sa.String(length=200), nullable=False),
        sa.Column('mime_type', sa.String(length=80), nullable=False),
        sa.Column('sha256', sa.String(length=64), nullable=False),
        sa.Column('source_label', sa.String(length=40), nullable=False),
        sa.Column('raw_text', sa.Text(), nullable=False),
        sa.Column('extraction_status', sa.String(length=24), nullable=False),
        sa.Column('uploaded_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_evidence_artifacts_extraction_status'), 'evidence_artifacts', ['extraction_status'], unique=False)
        op.create_index(op.f('ix_evidence_artifacts_incident_id'), 'evidence_artifacts', ['incident_id'], unique=False)
        op.create_index(op.f('ix_evidence_artifacts_merchant_id'), 'evidence_artifacts', ['merchant_id'], unique=False)
        op.create_index(op.f('ix_evidence_artifacts_sha256'), 'evidence_artifacts', ['sha256'], unique=False)
        op.create_index(op.f('ix_evidence_artifacts_tenant_id'), 'evidence_artifacts', ['tenant_id'], unique=False)
        op.create_index(op.f('ix_evidence_artifacts_uploaded_at'), 'evidence_artifacts', ['uploaded_at'], unique=False)
        op.create_table('financial_events',
        sa.Column('id', sa.String(length=40), nullable=False),
        sa.Column('event_type', sa.String(length=32), nullable=False),
        sa.Column('source_system', sa.String(length=32), nullable=False),
        sa.Column('source_record_id', sa.String(length=32), nullable=False),
        sa.Column('merchant_id', sa.String(length=32), nullable=False),
        sa.Column('actor_id', sa.String(length=32), nullable=False),
        sa.Column('account_id', sa.String(length=32), nullable=False),
        sa.Column('counterparty_id', sa.String(length=32), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('amount', sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column('currency', sa.String(length=8), nullable=False),
        sa.Column('attributes', app.models.entities.SafeJSON(), nullable=False),
        sa.Column('evidence_refs', app.models.entities.SafeJSON(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('extraction_method', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_fevent_merchant_ts', 'financial_events', ['merchant_id', 'timestamp'], unique=False)
        op.create_index(op.f('ix_financial_events_counterparty_id'), 'financial_events', ['counterparty_id'], unique=False)
        op.create_index(op.f('ix_financial_events_event_type'), 'financial_events', ['event_type'], unique=False)
        op.create_index(op.f('ix_financial_events_merchant_id'), 'financial_events', ['merchant_id'], unique=False)
        op.create_index(op.f('ix_financial_events_source_record_id'), 'financial_events', ['source_record_id'], unique=False)
        op.create_index(op.f('ix_financial_events_tenant_id'), 'financial_events', ['tenant_id'], unique=False)
        op.create_index(op.f('ix_financial_events_timestamp'), 'financial_events', ['timestamp'], unique=False)
        op.create_table('incidents',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('merchant_id', sa.String(length=32), nullable=False),
        sa.Column('state', sa.String(length=32), nullable=False),
        sa.Column('scenario', sa.String(length=48), nullable=False),
        sa.Column('incident_evidence_score', sa.Float(), nullable=False),
        sa.Column('score_components', app.models.entities.SafeJSON(), nullable=False),
        sa.Column('window_start', sa.DateTime(), nullable=True),
        sa.Column('window_end', sa.DateTime(), nullable=True),
        sa.Column('dataset_version', sa.String(length=24), nullable=False),
        sa.Column('config_version', sa.String(length=24), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('severity', sa.String(length=16), nullable=False),
        sa.Column('financial_exposure', sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column('recoverable_amount', sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column('unrecoverable_amount', sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('evidence_count', sa.Integer(), nullable=False),
        sa.Column('affected_entities', sa.Integer(), nullable=False),
        sa.Column('resolution_state', sa.String(length=24), nullable=False),
        sa.Column('tenant_id', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_incident_tenant', 'incidents', ['tenant_id'], unique=False)
        op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
        op.create_index(op.f('ix_incidents_merchant_id'), 'incidents', ['merchant_id'], unique=False)
        op.create_index(op.f('ix_incidents_state'), 'incidents', ['state'], unique=False)
        op.create_index(op.f('ix_incidents_tenant_id'), 'incidents', ['tenant_id'], unique=False)
        op.create_table('orders',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('merchant_id', sa.String(length=32), nullable=False),
        sa.Column('amount', sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column('currency', sa.String(length=8), nullable=False),
        sa.Column('status', sa.String(length=24), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
        op.create_index(op.f('ix_orders_merchant_id'), 'orders', ['merchant_id'], unique=False)
        op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
        op.create_table('settlements',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('merchant_id', sa.String(length=32), nullable=False),
        sa.Column('amount', sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column('status', sa.String(length=24), nullable=False),
        sa.Column('settlement_window_start', sa.DateTime(), nullable=False),
        sa.Column('settlement_window_end', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_settlements_created_at'), 'settlements', ['created_at'], unique=False)
        op.create_index(op.f('ix_settlements_merchant_id'), 'settlements', ['merchant_id'], unique=False)
        op.create_index(op.f('ix_settlements_tenant_id'), 'settlements', ['tenant_id'], unique=False)
        op.create_table('transfers',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('merchant_id', sa.String(length=32), nullable=False),
        sa.Column('source_payment_id', sa.String(length=32), nullable=False),
        sa.Column('destination_account_id', sa.String(length=32), nullable=False),
        sa.Column('amount', sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column('status', sa.String(length=24), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_transfers_created_at'), 'transfers', ['created_at'], unique=False)
        op.create_index(op.f('ix_transfers_merchant_id'), 'transfers', ['merchant_id'], unique=False)
        op.create_index(op.f('ix_transfers_tenant_id'), 'transfers', ['tenant_id'], unique=False)
        op.create_table('webhook_events',
        sa.Column('id', sa.String(length=40), nullable=False),
        sa.Column('event_type', sa.String(length=64), nullable=False),
        sa.Column('source_object_type', sa.String(length=32), nullable=False),
        sa.Column('source_object_id', sa.String(length=32), nullable=False),
        sa.Column('merchant_id', sa.String(length=32), nullable=False),
        sa.Column('payload', app.models.entities.SafeJSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_webhook_events_created_at'), 'webhook_events', ['created_at'], unique=False)
        op.create_index(op.f('ix_webhook_events_merchant_id'), 'webhook_events', ['merchant_id'], unique=False)
        op.create_index(op.f('ix_webhook_events_source_object_id'), 'webhook_events', ['source_object_id'], unique=False)
        op.create_index(op.f('ix_webhook_events_tenant_id'), 'webhook_events', ['tenant_id'], unique=False)
        op.create_table('communication_events',
        sa.Column('id', sa.String(length=40), nullable=False),
        sa.Column('source_artifact_id', sa.String(length=40), nullable=False),
        sa.Column('incident_id', sa.String(length=32), nullable=False),
        sa.Column('sender_label', sa.String(length=120), nullable=False),
        sa.Column('channel', sa.String(length=24), nullable=False),
        sa.Column('body_text', sa.Text(), nullable=False),
        sa.Column('mentioned_amount', sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column('mentioned_beneficiary_text', sa.String(length=160), nullable=False),
        sa.Column('resolved_contact_id', sa.String(length=32), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('correlation_status', sa.String(length=24), nullable=False),
        sa.Column('correlated_financial_event_id', sa.String(length=40), nullable=False),
        sa.Column('tenant_id', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['source_artifact_id'], ['evidence_artifacts.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_communication_events_incident_id'), 'communication_events', ['incident_id'], unique=False)
        op.create_index(op.f('ix_communication_events_source_artifact_id'), 'communication_events', ['source_artifact_id'], unique=False)
        op.create_index(op.f('ix_communication_events_tenant_id'), 'communication_events', ['tenant_id'], unique=False)
        op.create_index(op.f('ix_communication_events_timestamp'), 'communication_events', ['timestamp'], unique=False)
        op.create_table('extracted_claims',
        sa.Column('id', sa.String(length=40), nullable=False),
        sa.Column('source_artifact_id', sa.String(length=40), nullable=False),
        sa.Column('source_location', sa.String(length=120), nullable=False),
        sa.Column('extraction_method', sa.String(length=40), nullable=False),
        sa.Column('claim_type', sa.String(length=40), nullable=False),
        sa.Column('claim_value', app.models.entities.SafeJSON(), nullable=False),
        sa.Column('verification_status', sa.String(length=24), nullable=False),
        sa.Column('matched_financial_event_id', sa.String(length=40), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['source_artifact_id'], ['evidence_artifacts.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_extracted_claims_source_artifact_id'), 'extracted_claims', ['source_artifact_id'], unique=False)
        op.create_index(op.f('ix_extracted_claims_tenant_id'), 'extracted_claims', ['tenant_id'], unique=False)
        op.create_index(op.f('ix_extracted_claims_verification_status'), 'extracted_claims', ['verification_status'], unique=False)
        op.create_table('fund_accounts',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('contact_id', sa.String(length=32), nullable=False),
        sa.Column('account_type', sa.String(length=16), nullable=False),
        sa.Column('masked_bank_account', sa.String(length=40), nullable=False),
        sa.Column('masked_ifsc', sa.String(length=20), nullable=False),
        sa.Column('vpa', sa.String(length=80), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_fund_accounts_contact_id'), 'fund_accounts', ['contact_id'], unique=False)
        op.create_index(op.f('ix_fund_accounts_created_at'), 'fund_accounts', ['created_at'], unique=False)
        op.create_index(op.f('ix_fund_accounts_tenant_id'), 'fund_accounts', ['tenant_id'], unique=False)
        op.create_table('human_attestations',
        sa.Column('id', sa.String(length=40), nullable=False),
        sa.Column('incident_id', sa.String(length=32), nullable=False),
        sa.Column('question_id', sa.String(length=64), nullable=False),
        sa.Column('question_text', sa.String(length=300), nullable=False),
        sa.Column('answer', sa.String(length=16), nullable=False),
        sa.Column('note', sa.String(length=500), nullable=False),
        sa.Column('actor', sa.String(length=80), nullable=False),
        sa.Column('affected_predicate', sa.String(length=120), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_human_attestations_created_at'), 'human_attestations', ['created_at'], unique=False)
        op.create_index(op.f('ix_human_attestations_incident_id'), 'human_attestations', ['incident_id'], unique=False)
        op.create_index(op.f('ix_human_attestations_tenant_id'), 'human_attestations', ['tenant_id'], unique=False)
        op.create_table('incident_events',
        sa.Column('id', sa.String(length=40), nullable=False),
        sa.Column('incident_id', sa.String(length=32), nullable=False),
        sa.Column('financial_event_id', sa.String(length=40), nullable=False),
        sa.Column('role', sa.String(length=32), nullable=False),
        sa.Column('sequence', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['financial_event_id'], ['financial_events.id'], ),
        sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_incident_events_financial_event_id'), 'incident_events', ['financial_event_id'], unique=False)
        op.create_index(op.f('ix_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False)
        op.create_index(op.f('ix_incident_events_tenant_id'), 'incident_events', ['tenant_id'], unique=False)
        op.create_table('payments',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('order_id', sa.String(length=32), nullable=False),
        sa.Column('merchant_id', sa.String(length=32), nullable=False),
        sa.Column('customer_id', sa.String(length=32), nullable=False),
        sa.Column('amount', sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column('currency', sa.String(length=8), nullable=False),
        sa.Column('status', sa.String(length=24), nullable=False),
        sa.Column('method', sa.String(length=24), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
        op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
        op.create_index(op.f('ix_payments_merchant_id'), 'payments', ['merchant_id'], unique=False)
        op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
        op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
        op.create_table('recovery_commands',
        sa.Column('id', sa.String(length=40), nullable=False),
        sa.Column('incident_id', sa.String(length=32), nullable=False),
        sa.Column('action', sa.String(length=40), nullable=False),
        sa.Column('target_type', sa.String(length=32), nullable=False),
        sa.Column('target_id', sa.String(length=40), nullable=False),
        sa.Column('amount', sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column('reason', sa.String(length=400), nullable=False),
        sa.Column('supporting_evidence', app.models.entities.SafeJSON(), nullable=False),
        sa.Column('expected_effect', sa.String(length=400), nullable=False),
        sa.Column('risk', sa.String(length=16), nullable=False),
        sa.Column('reversible', sa.Boolean(), nullable=False),
        sa.Column('required_approval_role', sa.String(length=24), nullable=False),
        sa.Column('idempotency_key', sa.String(length=64), nullable=False),
        sa.Column('state', sa.String(length=24), nullable=False),
        sa.Column('created_by', sa.String(length=32), nullable=False),
        sa.Column('reviewed_by', sa.String(length=32), nullable=False),
        sa.Column('approved_by', sa.String(length=32), nullable=False),
        sa.Column('executed_at', sa.DateTime(), nullable=True),
        sa.Column('execution_mode', sa.String(length=16), nullable=False),
        sa.Column('dry_run_result', app.models.entities.SafeJSON(), nullable=False),
        sa.Column('execution_result', app.models.entities.SafeJSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_recovery_commands_created_at'), 'recovery_commands', ['created_at'], unique=False)
        op.create_index(op.f('ix_recovery_commands_idempotency_key'), 'recovery_commands', ['idempotency_key'], unique=True)
        op.create_index(op.f('ix_recovery_commands_incident_id'), 'recovery_commands', ['incident_id'], unique=False)
        op.create_index(op.f('ix_recovery_commands_state'), 'recovery_commands', ['state'], unique=False)
        op.create_index(op.f('ix_recovery_commands_tenant_id'), 'recovery_commands', ['tenant_id'], unique=False)
        op.create_table('payouts',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('merchant_id', sa.String(length=32), nullable=False),
        sa.Column('contact_id', sa.String(length=32), nullable=False),
        sa.Column('fund_account_id', sa.String(length=32), nullable=False),
        sa.Column('amount', sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column('currency', sa.String(length=8), nullable=False),
        sa.Column('purpose', sa.String(length=40), nullable=False),
        sa.Column('mode', sa.String(length=16), nullable=False),
        sa.Column('narration', sa.String(length=200), nullable=False),
        sa.Column('reference_id', sa.String(length=64), nullable=False),
        sa.Column('status', sa.String(length=24), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('is_injected', sa.Boolean(), nullable=False),
        sa.Column('tenant_id', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
        sa.ForeignKeyConstraint(['fund_account_id'], ['fund_accounts.id'], ),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_payout_merchant_created', 'payouts', ['merchant_id', 'created_at'], unique=False)
        op.create_index('ix_payout_tenant', 'payouts', ['tenant_id'], unique=False)
        op.create_index(op.f('ix_payouts_contact_id'), 'payouts', ['contact_id'], unique=False)
        op.create_index(op.f('ix_payouts_created_at'), 'payouts', ['created_at'], unique=False)
        op.create_index(op.f('ix_payouts_fund_account_id'), 'payouts', ['fund_account_id'], unique=False)
        op.create_index(op.f('ix_payouts_merchant_id'), 'payouts', ['merchant_id'], unique=False)
        op.create_index(op.f('ix_payouts_status'), 'payouts', ['status'], unique=False)
        op.create_index(op.f('ix_payouts_tenant_id'), 'payouts', ['tenant_id'], unique=False)
        # ### end Alembic commands ###
    
    
    else:
        # The database already has the previous architecture
        # 1. Create risk tables if they are missing
        if 'account_trust_states' not in tables:
            op.create_table('account_trust_states',
                sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                sa.Column('tenant_id', sa.String(), nullable=False),
                sa.Column('entity_id', sa.String(), nullable=False),
                sa.Column('known_devices', app.models.entities.SafeJSON(), nullable=False),
                sa.Column('known_ips', app.models.entities.SafeJSON(), nullable=False),
                sa.Column('known_beneficiaries', app.models.entities.SafeJSON(), nullable=False),
                sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
                sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
                sa.Column('median_amount', sa.Numeric(precision=24, scale=6), nullable=False),
                sa.Column('mad_amount', sa.Numeric(precision=24, scale=6), nullable=False),
                sa.Column('total_transactions', sa.Integer(), nullable=False),
                sa.Column('active_incident_id', sa.String(), nullable=True),
                sa.Column('current_risk_score', sa.Float(), nullable=False),
                sa.Column('first_divergence_at', sa.DateTime(timezone=True), nullable=True),
                sa.Column('last_event_hash', sa.String(), nullable=False),
                sa.Column('version', sa.Integer(), nullable=False),
                sa.PrimaryKeyConstraint('id'),
                sa.UniqueConstraint('tenant_id', 'entity_id', name='uq_trust_state_tenant_entity')
            )
        if 'graph_relationships' not in tables:
            op.create_table('graph_relationships',
                sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                sa.Column('tenant_id', sa.String(), nullable=False),
                sa.Column('source_type', sa.String(), nullable=False),
                sa.Column('source_id', sa.String(), nullable=False),
                sa.Column('target_type', sa.String(), nullable=False),
                sa.Column('target_id', sa.String(), nullable=False),
                sa.Column('relation_type', sa.String(), nullable=False),
                sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
                sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
                sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
                sa.PrimaryKeyConstraint('id')
            )
            op.create_index(op.f('ix_graph_relationships_tenant_id'), 'graph_relationships', ['tenant_id'], unique=False)
            op.create_index('ix_graph_source', 'graph_relationships', ['tenant_id', 'source_type', 'source_id'], unique=False)
            op.create_index('ix_graph_target', 'graph_relationships', ['tenant_id', 'target_type', 'target_id'], unique=False)
        if 'risk_decisions' not in tables:
            op.create_table('risk_decisions',
                sa.Column('decision_id', sa.String(), nullable=False),
                sa.Column('tenant_id', sa.String(), nullable=False),
                sa.Column('entity_id', sa.String(), nullable=False),
                sa.Column('event_id', sa.String(), nullable=False),
                sa.Column('risk_probability', sa.Float(), nullable=False),
                sa.Column('risk_band', sa.String(), nullable=False),
                sa.Column('recommended_action', sa.String(), nullable=False),
                sa.Column('reason_codes', app.models.entities.SafeJSON(), nullable=False),
                sa.Column('supporting_events', app.models.entities.SafeJSON(), nullable=False),
                sa.Column('competing_hypotheses', app.models.entities.SafeJSON(), nullable=False),
                sa.Column('model_version', sa.String(), nullable=False),
                sa.Column('policy_version', sa.String(), nullable=False),
                sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
                sa.Column('actual_outcome', sa.String(), nullable=True),
                sa.PrimaryKeyConstraint('decision_id')
            )
            op.create_index(op.f('ix_risk_decisions_entity_id'), 'risk_decisions', ['entity_id'], unique=False)
            op.create_index(op.f('ix_risk_decisions_tenant_id'), 'risk_decisions', ['tenant_id'], unique=False)
        if 'risk_events' not in tables:
            op.create_table('risk_events',
                sa.Column('event_id', sa.String(), nullable=False),
                sa.Column('tenant_id', sa.String(), nullable=False),
                sa.Column('entity_id', sa.String(), nullable=False),
                sa.Column('event_type', sa.String(), nullable=False),
                sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
                sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
                sa.Column('source', sa.String(), nullable=False),
                sa.Column('source_event_id', sa.String(), nullable=False),
                sa.Column('schema_version', sa.String(), nullable=False),
                sa.Column('payload', app.models.entities.SafeJSON(), nullable=False),
                sa.Column('payload_hash', sa.String(), nullable=False),
                sa.Column('previous_event_hash', sa.String(), nullable=False),
                sa.PrimaryKeyConstraint('event_id'),
                sa.UniqueConstraint('tenant_id', 'source', 'source_event_id', name='uq_risk_event_source')
            )
            op.create_index(op.f('ix_risk_events_entity_id'), 'risk_events', ['entity_id'], unique=False)
            op.create_index(op.f('ix_risk_events_event_time'), 'risk_events', ['event_time'], unique=False)
            op.create_index(op.f('ix_risk_events_event_type'), 'risk_events', ['event_type'], unique=False)
            op.create_index(op.f('ix_risk_events_tenant_id'), 'risk_events', ['tenant_id'], unique=False)

        # 2. Upgrade float columns to Numeric(24,6) if PostgreSQL
        if bind.dialect.name == 'postgresql':
            columns_to_upgrade = [
                ('payouts', 'amount'),
                ('payments', 'amount'),
                ('financial_events', 'amount'),
                ('account_trust_states', 'median_amount'),
                ('account_trust_states', 'mad_amount'),
                ('incidents', 'financial_exposure'),
                ('incidents', 'recoverable_amount'),
                ('incidents', 'unrecoverable_amount'),
                ('communication_events', 'mentioned_amount'),
                ('recovery_commands', 'amount'),
                ('settlements', 'amount'),
                ('transfers', 'amount'),
                ('orders', 'amount'),
            ]
            for table, col in columns_to_upgrade:
                if table in tables:
                    # Check if column exists to avoid ProgrammingError aborting transaction
                    existing_cols = [c['name'] for c in inspector.get_columns(table)]
                    if col in existing_cols:
                        op.execute(f"ALTER TABLE {table} ALTER COLUMN {col} TYPE NUMERIC(24,6) USING {col}::numeric")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payouts_tenant_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_status'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_merchant_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_fund_account_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_created_at'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_contact_id'), table_name='payouts')
    op.drop_index('ix_payout_tenant', table_name='payouts')
    op.drop_index('ix_payout_merchant_created', table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_recovery_commands_tenant_id'), table_name='recovery_commands')
    op.drop_index(op.f('ix_recovery_commands_state'), table_name='recovery_commands')
    op.drop_index(op.f('ix_recovery_commands_incident_id'), table_name='recovery_commands')
    op.drop_index(op.f('ix_recovery_commands_idempotency_key'), table_name='recovery_commands')
    op.drop_index(op.f('ix_recovery_commands_created_at'), table_name='recovery_commands')
    op.drop_table('recovery_commands')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_merchant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_incident_events_tenant_id'), table_name='incident_events')
    op.drop_index(op.f('ix_incident_events_incident_id'), table_name='incident_events')
    op.drop_index(op.f('ix_incident_events_financial_event_id'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_human_attestations_tenant_id'), table_name='human_attestations')
    op.drop_index(op.f('ix_human_attestations_incident_id'), table_name='human_attestations')
    op.drop_index(op.f('ix_human_attestations_created_at'), table_name='human_attestations')
    op.drop_table('human_attestations')
    op.drop_index(op.f('ix_fund_accounts_tenant_id'), table_name='fund_accounts')
    op.drop_index(op.f('ix_fund_accounts_created_at'), table_name='fund_accounts')
    op.drop_index(op.f('ix_fund_accounts_contact_id'), table_name='fund_accounts')
    op.drop_table('fund_accounts')
    op.drop_index(op.f('ix_extracted_claims_verification_status'), table_name='extracted_claims')
    op.drop_index(op.f('ix_extracted_claims_tenant_id'), table_name='extracted_claims')
    op.drop_index(op.f('ix_extracted_claims_source_artifact_id'), table_name='extracted_claims')
    op.drop_table('extracted_claims')
    op.drop_index(op.f('ix_communication_events_timestamp'), table_name='communication_events')
    op.drop_index(op.f('ix_communication_events_tenant_id'), table_name='communication_events')
    op.drop_index(op.f('ix_communication_events_source_artifact_id'), table_name='communication_events')
    op.drop_index(op.f('ix_communication_events_incident_id'), table_name='communication_events')
    op.drop_table('communication_events')
    op.drop_index(op.f('ix_webhook_events_tenant_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_source_object_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_merchant_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_created_at'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_transfers_tenant_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_merchant_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_created_at'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_settlements_tenant_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_merchant_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_created_at'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_merchant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_incidents_tenant_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_state'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_merchant_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_index('ix_incident_tenant', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_financial_events_timestamp'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_tenant_id'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_source_record_id'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_merchant_id'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_event_type'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_counterparty_id'), table_name='financial_events')
    op.drop_index('ix_fevent_merchant_ts', table_name='financial_events')
    op.drop_table('financial_events')
    op.drop_index(op.f('ix_evidence_artifacts_uploaded_at'), table_name='evidence_artifacts')
    op.drop_index(op.f('ix_evidence_artifacts_tenant_id'), table_name='evidence_artifacts')
    op.drop_index(op.f('ix_evidence_artifacts_sha256'), table_name='evidence_artifacts')
    op.drop_index(op.f('ix_evidence_artifacts_merchant_id'), table_name='evidence_artifacts')
    op.drop_index(op.f('ix_evidence_artifacts_incident_id'), table_name='evidence_artifacts')
    op.drop_index(op.f('ix_evidence_artifacts_extraction_status'), table_name='evidence_artifacts')
    op.drop_table('evidence_artifacts')
    op.drop_index(op.f('ix_employees_tenant_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_merchant_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_contacts_tenant_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_merchant_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_created_at'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_api_token'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_merchants_tenant_id'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_entity_links_tenant_id'), table_name='entity_links')
    op.drop_index(op.f('ix_entity_links_right_id'), table_name='entity_links')
    op.drop_index(op.f('ix_entity_links_left_id'), table_name='entity_links')
    op.drop_table('entity_links')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_incident_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_risk_events_tenant_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_event_type'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_event_time'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_entity_id'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_risk_decisions_tenant_id'), table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_entity_id'), table_name='risk_decisions')
    op.drop_table('risk_decisions')
    op.drop_index('ix_graph_target', table_name='graph_relationships')
    op.drop_index('ix_graph_source', table_name='graph_relationships')
    op.drop_index(op.f('ix_graph_relationships_tenant_id'), table_name='graph_relationships')
    op.drop_table('graph_relationships')
    op.drop_table('account_trust_states')
    # ### end Alembic commands ###
