"""Add risk models

Revision ID: c76234b99be6
Revises: 
Create Date: 2026-09-14 00:07:30.045422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app

# revision identifiers, used by Alembic.
revision: str = 'c76234b99be6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_trust_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('known_devices', app.models.risk.JSONVariant(), nullable=False),
    sa.Column('known_ips', app.models.risk.JSONVariant(), nullable=False),
    sa.Column('known_beneficiaries', app.models.risk.JSONVariant(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('median_amount', sa.Float(), nullable=False),
    sa.Column('mad_amount', sa.Float(), nullable=False),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('active_incident_id', sa.String(), nullable=True),
    sa.Column('current_risk_score', sa.Float(), nullable=False),
    sa.Column('first_divergence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_hash', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'entity_id', name='uq_trust_state_tenant_entity')
    )
    op.create_table('graph_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_relationships_tenant_id'), 'graph_relationships', ['tenant_id'], unique=False)
    op.create_index('ix_graph_source', 'graph_relationships', ['tenant_id', 'source_type', 'source_id'], unique=False)
    op.create_index('ix_graph_target', 'graph_relationships', ['tenant_id', 'target_type', 'target_id'], unique=False)
    op.create_table('risk_decisions',
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('risk_probability', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.String(), nullable=False),
    sa.Column('recommended_action', sa.String(), nullable=False),
    sa.Column('reason_codes', app.models.risk.JSONVariant(), nullable=False),
    sa.Column('supporting_events', app.models.risk.JSONVariant(), nullable=False),
    sa.Column('competing_hypotheses', app.models.risk.JSONVariant(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_outcome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index(op.f('ix_risk_decisions_entity_id'), 'risk_decisions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_risk_decisions_tenant_id'), 'risk_decisions', ['tenant_id'], unique=False)
    op.create_table('risk_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_event_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('payload', app.models.risk.JSONVariant(), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('previous_event_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('tenant_id', 'source', 'source_event_id', name='uq_risk_event_source')
    )
    op.create_index(op.f('ix_risk_events_entity_id'), 'risk_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_risk_events_event_time'), 'risk_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_risk_events_event_type'), 'risk_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_risk_events_tenant_id'), 'risk_events', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_events_tenant_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_event_type'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_event_time'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_entity_id'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_risk_decisions_tenant_id'), table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_entity_id'), table_name='risk_decisions')
    op.drop_table('risk_decisions')
    op.drop_index('ix_graph_target', table_name='graph_relationships')
    op.drop_index('ix_graph_source', table_name='graph_relationships')
    op.drop_index(op.f('ix_graph_relationships_tenant_id'), table_name='graph_relationships')
    op.drop_table('graph_relationships')
    op.drop_table('account_trust_states')
    # ### end Alembic commands ###
