import React from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Database, Users, ShieldCheck, Plus, Building2 } from "lucide-react";

export default function SaaS(){
 return <div className="min-h-[calc(100vh-64px)] bg-graphite text-text_primary"><div className="max-w-canvas mx-auto px-6 sm:px-10 py-10">
  <div className="max-w-3xl"><p className="label-eyebrow text-text_primary/35 mb-3">WORKSPACE · FIRST RUN</p><h1 className="font-display text-5xl tracking-tight">Your financial operations workspace.</h1><p className="text-base leading-relaxed text-text_primary/50 mt-4 max-w-2xl">This is your control plane, not a pre-filled demo. Set up your organization and connect authorized financial data before Primhora begins creating incidents.</p></div>
  <div className="mt-10 grid lg:grid-cols-[1.25fr_.75fr] gap-5">
   <section className="rounded-2xl border border-surface_border bg-surface p-7"><div className="flex items-start justify-between gap-6"><div><p className="label-eyebrow text-text_primary/35">GET STARTED</p><h2 className="font-display text-2xl mt-2">Build your workspace</h2></div><span className="rounded-full border border-amber/25 text-amber px-3 py-1.5 text-[10px] uppercase tracking-wider">Not connected</span></div>
    <div className="mt-8 space-y-3">{[["01","Set up your organization","Company identity, operating context and workspace ownership."],["02","Connect your data","Authorized payment, bank, ledger or file sources."],["03","Invite your team","Assign analyst, investigator and approver responsibilities."],["04","Start monitoring","Incidents appear only when your connected data creates them."]].map(([n,t,c],i)=><div key={n} className="flex gap-4 rounded-xl border border-surface_border p-4"><span className="font-ui text-xs text-text_primary/30 pt-1">{n}</span><div><p className="font-medium">{t}</p><p className="text-xs text-text_primary/40 mt-1">{c}</p></div>{i===0&&<span className="ml-auto text-xs text-text_primary/35">Start here</span>}</div>)}</div>
    <button className="mt-7 inline-flex items-center gap-2 rounded-xl bg-text_primary text-graphite px-5 py-3 text-sm font-medium"><Plus size={15}/> Create organization <ArrowRight size={14}/></button>
   </section>
   <aside className="space-y-3"><div className="rounded-2xl border border-surface_border bg-surface p-6"><Building2 size={18}/><p className="font-display text-xl mt-7">No organization yet</p><p className="text-xs leading-relaxed text-text_primary/45 mt-2">A new Primhora workspace starts empty. There are no clients, incidents or financial records here until you add them.</p></div>
    <Link to="/demo/setup" className="block rounded-2xl border border-amber/20 bg-amber/[0.04] p-6 hover:bg-amber/[0.07] transition"><ShieldCheck size={18} className="text-amber"/><p className="font-display text-xl mt-7">Want to see it working?</p><p className="text-xs leading-relaxed text-text_primary/45 mt-2">Open the synthetic demo and investigate a complete incident without connecting anything.</p><span className="inline-flex items-center gap-2 text-xs mt-5">Explore demo <ArrowRight size={13}/></span></Link>
   </aside>
  </div>
  <div className="mt-8 grid md:grid-cols-3 gap-3"><Link to="/app/data-sources" className="rounded-2xl border border-surface_border bg-surface p-5 hover:bg-surface_raised transition"><Database size={17}/><p className="font-display text-lg mt-7">Data sources</p><p className="text-xs text-text_primary/40 mt-1">Connect or import authorized records.</p></Link><Link to="/app/team" className="rounded-2xl border border-surface_border bg-surface p-5 hover:bg-surface_raised transition"><Users size={17}/><p className="font-display text-lg mt-7">Team & controls</p><p className="text-xs text-text_primary/40 mt-1">Prepare roles and approvals.</p></Link><div className="rounded-2xl border border-surface_border bg-surface p-5"><ShieldCheck size={17}/><p className="font-display text-lg mt-7">Governed recovery</p><p className="text-xs text-text_primary/40 mt-1">Recovery actions remain reviewable and auditable.</p></div></div>
 </div></div>;
}